# Generated by Django 4.0.4 on 2022-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stripe_price_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
