# Generated by Django 4.0.4 on 2022-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_price_stripe_price_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stripe_package',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
